config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :show do
      resources :answers, shallow: true, only: :show
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges, except: :update
    resources :gists, only: :index
  end

  resources :feedbacks, only: %i[new create]

  resources :badges, only: %i[index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :rule, class_name: 'BadgeRule'

  validates :title, presence: true
  validates :icon_url, presence: true
  validates :rule_id, presence: true
end

app/controllers/admin/badges_controller.rb
# frozen_string_literal: true

class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[show destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)
    @badge.save ? redirect_to(admin_badges_url) : render(:new)
  end

  def destroy
    @badge.destroy
    redirect_to(admin_badges_url)
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :icon_url, :rule_id)
  end
end

app/controllers/badges_controller.rb
# frozen_string_literal: true

class BadgesController < ApplicationController
  def index
    @user_badges = current_user.badges
    @all_badges = Badge.all
  end
end

app/views/admin/badges/_badge.html.erb
<p>
  <img class="badge_url" src="<%= badge.icon_url %>" alt="Значок" />
  <%= badge.title %>
  <%= link_to 'Открыть', admin_badge_path(badge) %>
  <%= link_to 'Удалить', admin_badge_path(badge),
              method: :delete,
              data: { confirm: "Вы уверены?" }
  %>
</p>

app/views/admin/badges/_form.html.erb
<%= form_with(model: [:admin, @badge], local: true) do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <p>
    <%= form.label :title, 'Название' %>
    <%= form.text_area :title, id: :badge_title %>
  </p>

  <p>
    <%= form.label :icon_url, 'URL картинки значка' %>
    <%= form.text_area :icon_url, id: :badge_icon_url %>
  </p>

  <p>
    <%= form.label :rule_id, 'Выберите правило получения' %>
    <%= form.collection_select :rule_id, BadgeRule.all, :id, :title, prompt: true, class: 'form-control' %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/admin/badges/index.html.erb
<section class="badge">
  <h2>Все бейджи</h2>

  <%= render @badges %>

  <%= link_to 'Создать бейдж', new_admin_badge_path(@badge) %>
</section>

app/views/admin/badges/new.html.erb
<h1>Создать новый бейдж</h1>


<%= render 'form' %>
<%= link_to 'Назад', admin_badges_path(@badge) %>

app/views/admin/badges/show.html.erb
<p>
  <h2>Название бейджа</h2>
  <%= @badge.title %>

  <h2>Иконка</h2>
  <img class="badge_url" src="<%= @badge.icon_url %>" alt="Значок" />
</p>

<p>
  <b>Правило получения: </b>
  <%= @badge.rule.title %>
</p>

<%= link_to 'Назад', admin_badges_path %>