config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :show do
      resources :answers, shallow: true, only: :show
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges, except: :update
    resources :gists, only: :index
  end

  resources :feedbacks, only: %i[new create]

  resources :badges, only: %i[index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  PASSAGE_SUCCESS_PERCENT = 85

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save
  end

  def completed?
    current_question.nil?
  end

  def result
    {
      total_questions_count: test.questions.size,
      correct_questions_count: self.correct_questions,
      correct_questions_percent: correct_questions_percent
    }
  end

  def end_time
    start_time + test.passage_time
  end

  def start_time
    created_at.to_i
  end

  def passage_time_expired?
    return false if test.passage_time.zero?

    Time.now.to_i > end_time
  end

  def question_number(question)
    self.test.questions.find_index(question) + 1
  end

  def succeed?
    return false if passage_time_expired?

    correct_questions_percent >= PASSAGE_SUCCESS_PERCENT
  end

  private

  def before_validation_set_next_question
    self.current_question = next_question
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_questions_percent
    (self.correct_questions.to_f / test.questions.size) * 100
  end

  def correct_answer?(answer_ids)
    answer_ids_count = answer_ids.nil? ? 0 : answer_ids.count
    correct_answers_count = correct_answers.count

    correct_answers_count == answer_ids_count &&
      correct_answers_count == correct_answers.where(id: answer_ids).count
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question&.id).first
  end
end

app/controllers/test_passages_controller.rb
# frozen_string_literal: true

class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]

  def show; end

  def result
    if @test_passage.succeed?
      @test_passage.successfully_passed = true
      @test_passage.save

      new_badges = BadgesService.new(@test_passage).handle_badges

      flash[:success] = 'У вас появились новые значки' if new_badges.present?
    end
  end

  def update
    return redirect_to(result_test_passage_path(@test_passage)) if @test_passage.passage_time_expired?

    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      # TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to(result_test_passage_path(@test_passage))
    else
      render(:show)
    end
  end

  def gist
    gist_service = GistQuestionService.new(@test_passage.current_question)
    response = gist_service.call

    if gist_service.success?
      gist = current_user.gists.create(
        question: @test_passage.current_question,
        url: response.data.url
      )

      gist.save
      flash_options = { notice: t('.success', link: response.data.url) }
    else
      flash_options = { notice: t('.failure') }
    end

    redirect_to @test_passage, flash_options
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1><%= t('.test_was_passed', title: @test_passage.test.title)  %></h1>

<p>
  <%= t('.questions_passed',
        count1: @test_passage.result[:correct_questions_count],
        count2: @test_passage.result[:total_questions_count]) %>
</p>

<p>
  <%= t('.test_result') %>:
  <% if @test_passage.succeed? %>
    <span style="color: green">
      <%= @test_passage.result[:correct_questions_percent] %>%
    </span>
    <%= t('.test_succeed') %>
  <% else %>
    <span style="color: red">
      <%= @test_passage.result[:correct_questions_percent] %>%
    </span>
    <%= t('.test_unsuccessful') %>
    <%= link_to t('buttons.repeat_test_button'), start_test_path(@test_passage.test), method: :post %>

    <% if @test_passage.passage_time_expired? %>
      <div>Вы не успели завершить тест за отведённое время</div>
    <% end %>
  <% end %>
</p>

<%= link_to t('buttons.to_tests_list_button'), tests_path, method: :get %>

app/views/test_passages/show.html.erb
<h1><%= t('.test_title', title: @test_passage.test.title) %></h1>
<span>
  <% if @test_passage.test.passage_time > 0 %>
    Время до завершения теста:
    <b class="timer" data-start-time="<%= @test_passage.start_time %>" data-end-time="<%= @test_passage.end_time %>">
      Осталось <span class="minutes"></span> минут и <span class="seconds"></span> секунд
    </b>
  <% else %>
    <b>У теста неограниченное время прохождения</b>
  <% end %>
</span>

<p>
  <b><%= t('.question_body', body: @test_passage.current_question.body) %></b>
</p>

<p>
  <%= t('.questions_answered',
        count1: @test_passage.question_number(@test_passage.current_question),
        count2: @test_passage.test.questions.size) %>
</p>

<div class="progress-bar">
  <div class="progress"></div>
</div>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form|  %>
  <%= form.collection_check_boxes :answer_ids,
                                  @test_passage.current_question.answers,
                                  :id,
                                  :body,
                                  include_hidden: false do |b| %>
    <%= b.check_box id: "answer_ids#{b.object.id}" %>
    <%= b.label %>
  <% end %>

  <p><%= link_to t('buttons.save_gist'), gist_test_passage_path(@test_passage), method: :post %></p>

  <input type="hidden"
         class="question-data"
         data-question-number="<%= @test_passage.question_number(@test_passage.current_question) %>"
         data-total-questions-count="<%= @test_passage.test.questions.size %>"
  />

  <p>
    <%= form.submit t('buttons.next_question_btn') %>
  </p>
<% end %>