config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :show do
      resources :answers, shallow: true, only: :show
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges, except: :update
    resources :gists, only: :index
  end

  resources :feedbacks, only: %i[new create]

  resources :badges, only: %i[index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  ANSWERS_MAX_COUNT = 4

  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_answers_count, on: :create

  private

  def validate_answers_count
    answers_count = question.nil? ? 0 : question.answers.count
    errors.add :message, "'Вопрос достиг максимального числа ответов'" if answers_count >= ANSWERS_MAX_COUNT
  end
end

app/controllers/admin/answers_controller.rb
# frozen_string_literal: true

class Admin::AnswersController < Admin::BaseController
  before_action :find_answer, only: %i[show edit update destroy]
  before_action :find_question, only: %i[new create]

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.save ? redirect_to(admin_answer_url(@answer)) : render(:new)
  end

  def update
    @answer.update(answer_params) ? redirect_to(admin_answer_url(@answer)) : render(:edit)
  end

  def destroy
    @answer.destroy
    redirect_to(admin_question_url(@answer.question))
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %>
  <%= link_to 'Показать', admin_answer_path(answer) %>
  <%= link_to 'Изменить', edit_admin_answer_path(answer) %>
  <%= link_to 'Удалить', admin_answer_path(answer),
                         method: :delete,
                         data: { confirm: "Вы уверены?" }
  %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with(model: [:admin, @question, @answer], local: true) do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body, 'Содержание' %>
    <%= form.text_area :body, id: :answer_body %>
  </p>

  <p>
    <%= form.label :correct, 'Правильный?' %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>Изменить ответ</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form' %>
<%= link_to 'Назад', admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1>Создать новый ответ</h1>

<p>
  <%= @question.body %>
</p>

<%= render 'form' %>
<%= link_to 'Назад', admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h1>Вопрос</h1>

<p>
  <%= @answer.question.body %>
</p>

<p>
  <b>Ответ: </b>
  <%= @answer.body %>
</p>

<p>
  <b>Правильный?: </b>
  <%= @answer.correct %>
</p>

<%= link_to 'Назад', admin_question_path(@answer.question) %>