config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }

  resources :tests, only: :index do
    resources :questions, shallow: true, only: :show do
      resources :answers, shallow: true, only: :show
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges, except: :update
    resources :gists, only: :index
  end

  resources :feedbacks, only: %i[new create]

  resources :badges, only: %i[index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div style="float: left">
      <span>Автор: Николай</span>
      <span><%= current_year %></span><br>
      <%= github_link('Xrazik1', 'test_guru') %>
      <p> - Приложение, позволяющее делиться тестами и решать их</p>
    </div>
    <div style="float: right">
      <p>Учебный проект в онлайн-школе: <a href="http://thinknetica.com/" target="_blank">Thinknetica</a></p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-light bg-light">
    <div class="navbar-brand">
      <%= link_to 'TestGuru', root_path %>
      <% if current_user&.admin? %>
        | <span style="font-weight: bold"><%= link_to 'Admin Panel', admin_tests_path %></span>
        | <span style="font-size: .7em"><%= link_to 'Show created gists', admin_gists_url %></span>
        | <span style="font-size: .7em"><%= link_to 'Show created badges', admin_badges_url %></span>
      <% end %>
      <% if user_signed_in? %>
        | <span style="font-size: .7em"><%= link_to 'Обратная связь', new_feedback_url %></span>
        | <span style="font-size: .7em"><%= link_to 'Ваши значки', badges_url %></span>
      <% end %>
    </div>
    <span class="navbar-text">
      <% if user_signed_in? %>
        Добро пожаловать, Гуру <b><%= current_user.name %> |
    </b> <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Регистрация', new_user_registration_path %>
        <%= link_to 'Вход', new_user_session_path %>
      <% end  %>
    </span>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>